### ISSUE TITLE
Support on Laravel 4.1

### ISSUE THREAD

**Issue by claudchan** [tournasdim/Laravel4-getgravatar#1]
Hi,
Will it support on latest Laravel 4.1?

**Comment by tournasdim** [comment]
I have just downloaded a Laravel 4.1 framework and seems it's not . I'll try to solve the issue . 
Merry Christmas , 
ps Today (December 25) , all Christians make the aforementioned wish , my intention is not to offend non-Christians .

**Comment by claudchan** [comment]
Merry Christmas to you too, Tournas.
Can't wait to have 4.1 support.

**Comment by tournasdim** [comment]
@claudchan 
Use  <b> "tournasdim/laravel4-getgravatar": "dev-master" </b> in your composer.json file (instead of  <b>tournasdim/laravel4-getgravatar": "*" </b>) . 

Thanks for reporting this bug :)

**Comment by claudchan** [comment]
Thank you!
Installations with composer update successful.
